#!/bin/bash

git branch -D KULRICE-4827-rice-release-2-0-br
git branch -D KULRICE-4879-rice-release-1-1-0-br
git branch -D KULRICE-4882-rice-release-1-1-0-br
git branch -D KULRICE-4883-rice-release-1-1-0-br
git branch -D KULRICE-4888-rice-release-1-1-0-br
git branch -D KULRICE-4889-rice-release-1-1-0-br
git branch -D KULRICE-4980-rice-release-1-1-0-br
git branch -D KULRICE-5050
git branch -D KULRICE-5069
git branch -D commons-project-merge-br
git branch -D docToHelpTest
git branch -D https%3A
git branch -D hudson-scm-poc
git branch -D ivy-release-0-9-2-br
git branch -D jasig-2008-rice-release-0-9-2-br
git branch -D jkeller-dd-refactor-merge-temp-br
git branch -D kns_config-br
git branch -D ksb-0-9-fix-work-br
git branch -D m1-1
git branch -D modularization-and-configuration
git branch -D new_branch
git branch -D new_branch@15219
git branch -D release-0-9-0-1-br
git branch -D release-0-9-0-1-ksb-fix-2-br
git branch -D release-0-9-0-1-ksb-fix-br
git branch -D release-0-9-1-br
git branch -D release-0-9-2-br
git branch -D release-0-9-br
git branch -D release-0-9-kim-br
git branch -D rice-1-0-0-scm-br
git branch -D rice-1-1-0-KULRICE-4850-br
git branch -D rice-1-1-0-KULRICE-4862-br
git branch -D rice-1-1-0-KULRICE-4870-br
git branch -D rice-1.0.3.3
git branch -D rice-2.0-KC
git branch -D rice-2.0-b6
git branch -D rice-2.1-kc
git branch -D rice-2.1-kfs
git branch -D rice-2.1-kfs@34908
git branch -D rice-2.1-kfs@35209
git branch -D rice-2.1-kfs@35567
git branch -D rice-2.1-msu
git branch -D rice-2.1-ooi
git branch -D rice-2.1.1
git branch -D rice-2.2-h2
git branch -D rice-2.2-myplan
git branch -D rice-2.2-tmp
git branch -D rice-2.3@45387
git branch -D rice-2.3@45453
git branch -D rice-m1-br
git branch -D rice-release-0-9-0-2-br
git branch -D rice-release-0-9-0-2-pre-param-refactor-br
git branch -D rice-release-0-9-0-3-br
git branch -D rice-release-0-9-0-4-br
git branch -D rice-release-0-9-1-1-br
git branch -D rice-release-0-9-1-2-br
git branch -D rice-release-0-9-1-3-br
git branch -D rice-release-0-9-1-4-br
git branch -D rice-release-0-9-2-1-br
git branch -D rice-release-0-9-2-kfs-performance-br
git branch -D rice-release-0-9-3-1-br
git branch -D rice-release-0-9-3-ahamid-dev-br
git branch -D rice-release-0-9-3-ahamid_dev-br
git branch -D rice-release-0-9-3-br
git branch -D rice-release-0-9-3-dd-refactor-br
git branch -D rice-release-0-9-3-jpa-br
git branch -D rice-release-0-9-3-jpa-merge-br
git branch -D rice-release-0-9-3-kfs-080211-br
git branch -D rice-release-0-9-3-kfs-080319-br
git branch -D rice-release-0-9-3-kfs-080522-br
git branch -D rice-release-0-9-3-kfs-080522-extract-br
git branch -D rice-release-0-9-3-kfs-extract-br
git branch -D rice-release-0-9-3-kra-br
git branch -D rice-release-0-9-3-pre-kfs-dd-merge-br
git branch -D rice-release-0-9-4-br
git branch -D rice-release-0-9-4-cas-br
git branch -D rice-release-0-9-4-db-refactor-br
git branch -D rice-release-0-9-4-facetoface-br
git branch -D rice-release-0-9-4-facetoface-merge-br
git branch -D rice-release-0-9-4-kfs-080702-br
git branch -D rice-release-0-9-4-kfs-080813-br
git branch -D rice-release-0-9-4-kfs-080813-uuconversion-br
git branch -D rice-release-0-9-4-ks-080827-br
git branch -D rice-release-0-9-4-person-group-2-br
git branch -D rice-release-0-9-4-scm-br
git branch -D rice-release-0-9-4-stable-br
git branch -D rice-release-0-9-4-usergroupconversion-br
git branch -D rice-release-1-0-0-KS-M1
git branch -D rice-release-1-0-0-br
git branch -D rice-release-1-0-0-scm-br
git branch -D rice-release-1-0-1-1-br
git branch -D rice-release-1-0-1-1-br@9932
git branch -D rice-release-1-0-1-1-liquibase-br
git branch -D rice-release-1-0-1-br
git branch -D rice-release-1-0-1-doc-search-br
git branch -D rice-release-1-0-2-1-br
git branch -D rice-release-1-0-2-br
git branch -D rice-release-1-0-3-1-br
git branch -D rice-release-1-0-3-1-ks-perf-br
git branch -D rice-release-1-0-3-2-br
git branch -D rice-release-1-0-3-br
git branch -D rice-release-1-0-kc-br
git branch -D rice-release-1-1-0-JPA-br
git branch -D rice-release-1-1-0-br
git branch -D rice-release-1-1-0-br-vc
git branch -D rice-release-1-1-0-itests-profile-br
git branch -D rice-release-1-1-0-james-jpa-maint-ojb-copy-br
git branch -D rice-release-1-1-0-jjh-test-br
git branch -D rice-release-1-1-0-kcfe-br
git branch -D rice-release-1-1-0-krad-br
git branch -D rice-release-1-1-0-mvn-integration-br
git branch -D rice-release-1-1-0-ria-pdf-work-br
git branch -D rice-release-1-1-0-test-jjh-br
git branch -D rice-release-1-1-0-vc-groovy-br
git branch -D rice-release-1-1-0-vc-groovy2-br
git branch -D rice-release-1-1-0-version-compat-br
git branch -D rice-release-2-0-0-krad-merge-br
git branch -D rice-release-2.0.0-m2-tag
git branch -D rice-release-kc-equivalence-br
git branch -D rice-scm-poc
git branch -D rice-sys-param-work-br
git branch -D rice.1.0
git branch -D sandbox
git branch -D testjjh
git branch -D training
git branch -D trunk-bak
git branch -D trunk@21199
git branch -D trunk@21209
git branch -D trunk@36228
git branch -D trunk@37665
git branch -D vc-interface-poc-1-1-xsany
git branch -D vc-interface-poc-1-1-xsany@15496
git branch -D versioning-poc-1-1-0-br
git branch -D versioning-poc2-1-1-0-br
git branch -D versioning-poc3-1-1-0-br
